title: Kadafi's Blog
tagline: Blog about computer science and mathematics 
description: A blog dedicated to share my knowledge and opinion related to computer science and mathematics
author: Muhamad Rizki Kadafi
logo: /assets/image/favicon.png
social:
  name: Muhamad Rizki Kadafi
  links:
    - https://www.linkedin.com/in/rizkikadafi 
    - https://github.com/rizkikadafi
baseurl: "/blog"
url: ""
defaults:
  - scope:
      path: ''
      type: posts
    values:
      permalink: /:categories/:title
      author: "Rizki Kadafi"
      layout: post
  - scope:
      path: '/assets/image/post-assets'
    values:
      post_asset: true
  - scope:
      path: ""
    values:
      toc: true

postcss:
  cache: false

plugins:
  - jekyll-postcss
  - jekyll-figure
  - jekyll-toc

jekyll-figure:
  paragraphs: false

exclude:
  - package.json
  - postcss.config.js
  - tailwind.config.js
  - package-lock.json
